# docker-compose.yml
services:  # Список сервисов (контейнеров)
  # FastAPI приложение
  web:
    build:   # Сборка из Dockerfile в текущей папке
      context: .
      dockerfile: Dockerfile
    image: sem87sem/translator:latest # или из имейдж
    container_name: translator  # Имя контейнера
    ports:
      - "30:8000"  # "хост:контейнер"
    environment:  # Переменные окружения
      - DOCKER_ENV=true  # Флаг для отключения reload
#      - DATABASE_URL=sqlite:///./app/books.db
    env_file:
      - .env
    volumes:  # Монтирование папок
      - semen-data:/app/semen
#      - books-db:/app/books.db
#      - jey:/app/jey.json
      - ./jey.json:/app/jey.json  # Мой джесон
      - ./books.db:/app/books.db # управляем базой данных
    restart: unless-stopped  # Перезапуск при падении

volumes:
  semen-data:
    driver: local
#  networks:
#    app_network:
#      driver: bridge
